
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
      - ./backend/uploads:/app/uploads
      - ./backend/converted:/app/converted
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
      
  celery:
    build:
      context: ./backend
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - ./backend:/backend
      - ./backend/uploads:/app/uploads
      - ./backend/converted:/app/converted
    depends_on:
      - backend
      - redis
      - rabbitmq
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend


volumes:
  postgres_data: